version: "3"

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=dev

  frontend-deploy:
    build:
      context: .
      dockerfile: Deploy.Dockerfile
    container_name: portfolio-frontend-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=prod