version: "3"

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=dev

  frontend-deploy:
    build:
      context: .
      dockerfile: Deploy.Dockerfile
    container_name: portfolio-frontend-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=prod
      - GITHUB_API_TOKEN=sometokenhere

  api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: portfolio-api-dev
    ports:
      - "8080:8080"
    env_file:
      - path: ./api/.env
        required: true
    environment:
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DISCORD_BOT_ID=${DISCORD_BOT_ID}
      - DISCORD_AUTH_TOKEN=${DISCORD_AUTH_TOKEN}
    volumes:
      - ./api:/app