// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutmeDocumentDataSlicesSlice = TextBlockSlice;

/**
 * Content for AboutMe documents
 */
interface AboutmeDocumentData {
  /**
   * Slice Zone field in *AboutMe*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutmeDocumentDataSlicesSlice> /**
   * Meta Title field in *AboutMe*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: aboutme.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *AboutMe*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: aboutme.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *AboutMe*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutme.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * AboutMe document from Prismic
 *
 * - **API ID**: `aboutme`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutmeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutmeDocumentData>,
    "aboutme",
    Lang
  >;

type FootercontentDocumentDataSlicesSlice = TextBlockSlice;

/**
 * Content for footercontent documents
 */
interface FootercontentDocumentData {
  /**
   * Slice Zone field in *footercontent*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footercontent.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FootercontentDocumentDataSlicesSlice> /**
   * Meta Title field in *footercontent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: footercontent.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *footercontent*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: footercontent.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *footercontent*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footercontent.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * footercontent document from Prismic
 *
 * - **API ID**: `footercontent`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FootercontentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FootercontentDocumentData>,
    "footercontent",
    Lang
  >;

/**
 * Item in *ReusableExperience → skills*
 */
export interface ReusableexperienceDocumentDataSkillsItem {
  /**
   * skill field in *ReusableExperience → skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusableexperience.skills[].skill
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  skill: prismic.KeyTextField;
}

/**
 * Content for ReusableExperience documents
 */
interface ReusableexperienceDocumentData {
  /**
   * title field in *ReusableExperience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusableexperience.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *ReusableExperience*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusableexperience.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * start field in *ReusableExperience*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: reusableexperience.start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start: prismic.DateField;

  /**
   * end field in *ReusableExperience*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: reusableexperience.end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end: prismic.DateField;

  /**
   * active field in *ReusableExperience*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: reusableexperience.active
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  active: prismic.BooleanField;

  /**
   * skills field in *ReusableExperience*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reusableexperience.skills[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<
    Simplify<ReusableexperienceDocumentDataSkillsItem>
  >;

  /**
   * institute field in *ReusableExperience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusableexperience.institute
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  institute: prismic.KeyTextField;

  /**
   * location field in *ReusableExperience*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: reusableexperience.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;
}

/**
 * ReusableExperience document from Prismic
 *
 * - **API ID**: `reusableexperience`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReusableexperienceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReusableexperienceDocumentData>,
    "reusableexperience",
    Lang
  >;

/**
 * Item in *SideProject → externalurls*
 */
export interface SideprojectDocumentDataExternalurlsItem {
  /**
   * externalurl field in *SideProject → externalurls*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sideproject.externalurls[].externalurl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  externalurl: prismic.LinkField;
}

/**
 * Content for SideProject documents
 */
interface SideprojectDocumentData {
  /**
   * image field in *SideProject*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sideproject.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *SideProject*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sideproject.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *SideProject*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sideproject.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * externalurls field in *SideProject*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sideproject.externalurls[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  externalurls: prismic.GroupField<
    Simplify<SideprojectDocumentDataExternalurlsItem>
  >;

  /**
   * start field in *SideProject*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: sideproject.start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start: prismic.DateField;

  /**
   * end field in *SideProject*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: sideproject.end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end: prismic.DateField;
}

/**
 * SideProject document from Prismic
 *
 * - **API ID**: `sideproject`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SideprojectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SideprojectDocumentData>,
    "sideproject",
    Lang
  >;

type SkillsDocumentDataSlicesSlice = SkillSlice;

/**
 * Content for skills documents
 */
interface SkillsDocumentData {
  /**
   * Slice Zone field in *skills*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SkillsDocumentDataSlicesSlice> /**
   * Meta Title field in *skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: skills.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *skills*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: skills.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *skills*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skills.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * skills document from Prismic
 *
 * - **API ID**: `skills`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SkillsDocumentData>, "skills", Lang>;

export type AllDocumentTypes =
  | AboutmeDocument
  | FootercontentDocument
  | ReusableexperienceDocument
  | SideprojectDocument
  | SkillsDocument;

/**
 * Default variation for Skill Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Skill*
 */
type SkillSliceVariation = SkillSliceDefault;

/**
 * Skill Shared Slice
 *
 * - **API ID**: `skill`
 * - **Description**: Skill
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SkillSlice = prismic.SharedSlice<"skill", SkillSliceVariation>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * TextBlock field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.textblock
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textblock: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutmeDocument,
      AboutmeDocumentData,
      AboutmeDocumentDataSlicesSlice,
      FootercontentDocument,
      FootercontentDocumentData,
      FootercontentDocumentDataSlicesSlice,
      ReusableexperienceDocument,
      ReusableexperienceDocumentData,
      ReusableexperienceDocumentDataSkillsItem,
      SideprojectDocument,
      SideprojectDocumentData,
      SideprojectDocumentDataExternalurlsItem,
      SkillsDocument,
      SkillsDocumentData,
      SkillsDocumentDataSlicesSlice,
      AllDocumentTypes,
      SkillSlice,
      SkillSliceVariation,
      SkillSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
