name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "VITE_GITHUB_API_TOKEN=${{ secrets.VITE_GITHUB_API_TOKEN }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Deploy.Dockerfile
          push: true
          tags: romori1993/portfolio-site-frontend-deploy:latest
          build-args: |
            VITE_GITHUB_API_TOKEN=${{ secrets.VITE_GITHUB_API_TOKEN }}
