name: Build and Push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./portfolio-frontend
          file: ./portfolio-frontend/Deploy.Dockerfile
          push: true
          tags: romori1993/portfolio-site-frontend-deploy:latest

      - name: Build and push api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api/Deploy.Dockerfile
          push: true
          tags: romori1993/portfolio-site-api-deploy:latest